### ISSUE TITLE
Information about the service and trip request form

### ISSUE THREAD

**Issue by rogadev** [rogadev/capstone#70]
Scenario: Visitors view information about the service and click on the call-to-action button to request a trip

    Given a visitor is on the website
    When they want to learn about the service
    Then they should be able to view information about the service
    And they should be able to see a call-to-action button to request a trip
    And the call-to-action button should be clickable
    And the button should redirect the visitor to the trip request form

### To-do Tasks
- [x] Add information about the service to the website
- [x] Create a call-to-action button on the website
- [x] Make sure the button redirects the visitor to the trip request form

**Comment by rogadev** [comment]
This user story was created for 276 assignment. The task has already been completed. Will mark as complete after marking.
