### ISSUE TITLE
Trip request form requirements and confirmation time

### ISSUE THREAD

**Issue by rogadev** [rogadev/capstone#71]
Scenario: Visitors want to know the requirements for submitting a trip request form

    Given a visitor is on the trip request form page
    When they want to learn about the requirements
    Then they should be able to see that trip requests need to be booked more than 36 hours in advance
    And they should be able to see that it may take up to 12 hours to confirm the trip request

Scenario: Visitors want to know that their form was submitted successfully and that they will be contacted

    Given a visitor has submitted a trip request form
    When they want to know if the form was submitted successfully
    Then they should be able to see a confirmation message that the form was submitted
    And they should be informed that someone will contact them shortly

## To-do Tasks
- [x] Add trip request form requirements to the website
- [ ] Add confirmation message to the website after a form is submitted
- [ ] Make sure that the confirmation message includes information about someone contacting the visitor shortly

**Comment by rogadev** [comment]
Pivoting to remove public trip requests. Only concerned with driver-input tasks. The current workflow would be that I am contacted by email or phone and trips are requested that way.
