### ISSUE TITLE
User authentication and authorization

### ISSUE THREAD

**Issue by rogadev** [rogadev/capstone#72]
Scenario: Only authorized users can log in and access the dashboard page

    Given a visitor is on the login page
    When they try to log in with the Google provider
    Then they should only be able to log in if they are an existing user
    And they should be redirected to the dashboard page if they are the correct user
    And they should not be able to log in if they are not the correct user
    And they should not be able to create a new user account

## To-do Tasks
- [x] Enable only the Google provider for OAuth login in Supabase settings
- [x] Turn off the ability to create new users in Supabase settings
- [x] Add code to check if the logging in user is the correct user and redirect them to the dashboard page if they are authorized
- [x] Add code to prevent logging in and account creation for unauthorized users

**Comment by rogadev** [comment]
This task is currently complete. Leaving it up until user stories is marked.
