### ISSUE TITLE
Confirm Requests page

### ISSUE THREAD

**Issue by rogadev** [rogadev/capstone#74]
Scenario: Users can confirm requests on the "Confirm Requests" page

    Given an authenticated user is on the "Confirm Requests" page
    When they view the submitted requests
    Then they should be able to look over the request details
    And they should be able to contact the client and confirm the trip
    And they should be able to approve or reject the trip

## To-do Tasks
- [x] Create a "Confirm Requests" page
- [x] Display submitted requests on the page
- [x] Add code to allow users to contact the client and confirm the trip
- [x] Add code to allow users to approve or reject the trip

**Comment by rogadev** [comment]
Should be finished last step today.

**Comment by rogadev** [comment]
Confirming trips successfully.
