### ISSUE TITLE
Schedule approved trips page

### ISSUE THREAD

**Issue by rogadev** [rogadev/capstone#75]
Scenario: Users can schedule approved trips on a separate page

    Given an authenticated user is on the "Schedule Trips" page
    When they view the approved trips
    Then they should be able to schedule the trip

## To-do Tasks
- [x] Create a "Schedule Trips" page
- [x] Display approved trips on the page
- [x] Add code to allow users to schedule the trip

**Comment by rogadev** [comment]
Modifying slightly to a "confirmed" page. This is where we can confirm, edit, or delete trips before putting them into our driving route. Confirming will create "stops" which will determine the flow of the actual driving usage.
