### ISSUE TITLE
Enter email snippets for formatting

### ISSUE THREAD

**Issue by rogadev** [rogadev/capstone#76]
Scenario: Users can enter email snippets that get sent off to ChatGPT for formatting

    Given an authenticated user is on the "Enter Email Snippets" page
    When they enter an email snippet
    Then it should be sent off to ChatGPT via their API for formatting
    And a formatted block of JSON should be received
    And the formatted block of JSON should be validated before trying to use it to populate a list of input fields

## To-do Tasks
- [x] Create an "Enter Email Snippets" page
- [x] Add code to send off the email snippet to ChatGPT via their API
- [x] Add code to receive the formatted block of JSON
- [x] Add code to validate the formatted block of JSON before using it to populate input fields

**Comment by rogadev** [comment]
Working!
