### ISSUE TITLE
Commit trips to the database and schedule them

### ISSUE THREAD

**Issue by rogadev** [rogadev/capstone#77]
Scenario: Users can commit trips to the database on a form and schedule the trips

    Given an authenticated user is on the "Schedule Trips" page
    When they enter the details of a trip in a form
    And they make changes to any of the fields of information
    Then they should be able to save the changes
    And the trip should be committed to the database
    And the trip should become visible on the

## To-do Tasks
- [x] Add a form for entering the details of a trip
- [x] Add code to enable the "save changes" button once changes are made to any of the fields of information
- [x] Add code to commit the trip to the database
- [x] Add code to display the trip on the page to schedule the trips after it has been committed to the database

**Comment by rogadev** [comment]
This is now working as intended. Trips are being generated by OpenAI API and, upon review and confirm, are saved to the database.
